### ISSUE TITLE
Will this build on Windows?

### ISSUE THREAD

**Issue by tyeeman** [y-yagi/mdv#4]
I should give it a try. Thanks for writing it.

**Comment by y-yagi** [comment]
Thanks for your issue. First, I'm not a Windows user. So I can't check whether this works on Windows.  

But, anyway, I released a binary for Windows. Please get a file from https://github.com/y-yagi/mdv/releases/tag/v0.2.0 
If there is any problem, please let me know. Thanks.

**Comment by tyeeman** [comment]
Thanks! Yes, it's working except my images in the same folder as my md file don't show at all. Do you know why?

**Comment by y-yagi** [comment]
Thanks for trying. I didn't support serving local files before. 
I fixed that and released the new version.
Please try it with specifying a `dir` option like follows. 

```bash 
mdv -dir . <filename>
```

**Comment by tyeeman** [comment]
Very nice, it works fine although the background is black. Is that normal? Maybe another option would be -background white/black. Only one other option I need is to use my own styling, so ``` -css style.css ``` would work great. I guess if -css is used then the background option is not needed?

**Comment by y-yagi** [comment]
> the background is black. Is that normal?  

Currently, `mdv` depends on the OS settings for the background color. Have you enabled dark mode on your OS?  Or, would you like to force the background color in the tool? 

> I need is to use my own styling,

The custom CSS is considering. I'm curious, in that case, do you want to specify a local CSS file?

**Comment by tyeeman** [comment]
Yes  if I could  force the background it would be better, and yes I would like to use a local css file. That's what I meant with "-css=style.css" as a command line option.

**Comment by tyeeman** [comment]
On second thought,  what is even better would be a template option  "-template=name.html". I could use my own template which has styling internal or external. I would need to add a tag somewhere in my template for where the converted markdown would go, something like ```$content$``` or equivalent. What do you think?

**Comment by y-yagi** [comment]
I thought, but template overriding seems a bit overkill right now. I'll think about it more later. 
Anyway, I've added the support for a custom style. You can now specify a CSS file as `mdv -css <CSS file> <markdown file>`.

**Comment by tyeeman** [comment]
OK, thanks. I just tried it and it works although I need to disable the internal stylesheet also while mine takes over. This one needs to be disabled - 
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.1.0/github-markdown.min.css">
```
Can you add if -css is used, disable internal stylesheet.

**Comment by y-yagi** [comment]
Oh, I misunderstood your use case. I changed the behavior that doesn't use any internal style if `css` option is specified.

**Comment by tyeeman** [comment]
Great! It's working just how I need it. Thanks a lot for all your work! Merry Xmas too.

**Comment by y-yagi** [comment]
Thanks for your great support. Merry Xmas to you too.
